
//IF YOU ARE NOT ON THE FLIGHT COMPUTER TEAM, ONLY CHANGE THESE VALUES ON THE RIGHT
//DO NOT MESS WITH THE CODE, TALK TO CHIEF ELECTRICAL ENGINEER IF YOU NEED SOMETHING 
//THAT IS NOT SPECIFIED
#define TWO_STAGE_ROCKET    True
#define MAIN_ALTITUDE       500